"""Compatibility exports for callers predating the data_objects package.

New production code imports the specific module. No business logic belongs here.
"""
from app.services.data_objects.definitions import DataObjectError as DataObjectError
from app.services.data_objects.definitions import HASH_FULL as HASH_FULL
from app.services.data_objects.definitions import HASH_PARTIAL as HASH_PARTIAL
from app.services.data_objects.definitions import HASH_SCOPED as HASH_SCOPED
from app.services.data_objects.definitions import IDENTITY_FULL as IDENTITY_FULL
from app.services.data_objects.definitions import IDENTITY_PARTIAL as IDENTITY_PARTIAL
from app.services.data_objects.definitions import IDENTITY_SCOPED as IDENTITY_SCOPED
from app.services.data_objects.definitions import INSTANCE_ACTIVE as INSTANCE_ACTIVE
from app.services.data_objects.definitions import INSTANCE_NOT_OBSERVED as INSTANCE_NOT_OBSERVED
from app.services.data_objects.definitions import INSTANCE_RESERVED as INSTANCE_RESERVED
from app.services.data_objects.definitions import MAX_SUMMARY_ROWS as MAX_SUMMARY_ROWS
from app.services.data_objects.definitions import REPORT_SCHEMA_SUPPORTED as REPORT_SCHEMA_SUPPORTED
from app.services.data_objects.definitions import SCOPED_KEY_SALT as SCOPED_KEY_SALT
from app.services.data_objects.definitions import _HEX64 as _HEX64
from app.services.data_objects.definitions import _HEX_DIGEST as _HEX_DIGEST
from app.services.data_objects.definitions import _SEVERITY_RANK as _SEVERITY_RANK
from app.services.data_objects.projection import _asset_type_for as _asset_type_for
from app.services.data_objects.values import _aware as _aware
from app.services.data_objects.evidence import _evidence_rows as _evidence_rows
from app.services.data_objects.values import _float as _float
from app.services.data_objects.persistence import _get_or_create as _get_or_create
from app.services.data_objects.values import _int as _int
from app.services.data_objects.coverage import _is_late as _is_late
from app.services.data_objects.values import _iso as _iso
from app.services.data_objects.projection import _looks_like_category as _looks_like_category
from app.services.data_objects.evidence import _merge_detection as _merge_detection
from app.services.data_objects.evidence import _merge_evidence as _merge_evidence
from app.services.data_objects.values import _newest as _newest
from app.services.data_objects.values import _parse_time as _parse_time
from app.services.data_objects.projection import _reported_sensitivity as _reported_sensitivity
from app.services.data_objects.values import _text as _text
from app.services.data_objects.queries import _type_scope as _type_scope
from app.services.data_objects.projection import backfill_legacy as backfill_legacy
from app.services.data_objects.values import category_name as category_name
from app.services.data_objects.coverage import complete_scope as complete_scope
from app.services.data_objects.queries import data_type_rows as data_type_rows
from app.services.data_objects.queries import data_type_summary as data_type_summary
from app.services.data_objects.values import detect_report_schema as detect_report_schema
from app.services.data_objects.evidence import evidence_key as evidence_key
from app.services.data_objects.persistence import forget_probe as forget_probe
from app.services.data_objects.coverage import in_scope as in_scope
from app.services.data_objects.ingestion import ingest_report as ingest_report
from app.services.data_objects.queries import instance_detail as instance_detail
from app.services.data_objects.identity import instance_type_for as instance_type_for
from app.services.data_objects.projection import mark_projection_not_observed as mark_projection_not_observed
from app.services.data_objects.identity import normalise_path as normalise_path
from app.services.data_objects.queries import object_detail as object_detail
from app.services.data_objects.identity import object_type_for as object_type_for
from app.services.data_objects.projection import project_asset as project_asset
from app.services.data_objects.projection import rebuild_projection as rebuild_projection
from app.services.data_objects.persistence import recount_object as recount_object
from app.services.data_objects.identity import resolve_identity as resolve_identity
from app.services.data_objects.identity import scope_key_for as scope_key_for
from app.services.data_objects.ingestion import sweep_scope as sweep_scope
